### ISSUE TITLE
Formatters for DataFrame to be used in Jupyter Notebook using dotnet interactive

### ISSUE THREAD

**Issue by praveenraghuvanshi1512** [bhrnjica/daany#5]
Great library!!!

Q1: Is there a sample present to transform a DataFrame into HTML table so that it can render properly in Jupyter notebook with dotnet interactive. Something similar to [An Introduction to DataFrame](https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/). 

Q2: How do we do GroupBy on multiple columns in a DataFrame, something similar to [link](https://www.datasciencemadesimple.com/group-by-sum-in-pandas-dataframe-python-2/)

**Comment by bhrnjica** [comment]
Thank you for using Daany:

A1.  https://github.com/bhrnjica/notebooks - is the repo where you can find formatting Daany.DataFrame into HTML. It worked in the previous versions of .NET interactive and Jupyter Notebook. Recently they have changes the API, and I am not sure if it is working. However, in the next weeks I am planing to release the new version in order to fix those incompatibilities.
 
A2. [Developer Guide for Daany](https://github.com/bhrnjica/daany/blob/master/docs/DevGuide/developer_guide.md) contans all supported features in Daany.DataFrame. Also if you download the source in UnitTest you can find the answer.

Hope this will help.

**Comment by bhrnjica** [comment]
Addition to A1: Here is a working example how to Format the DataFrame:

![Screenshot_20210615_073117](https://user-images.githubusercontent.com/1240016/121998121-b1249b00-cdab-11eb-84c0-fbe62db0cd36.png)
